### ISSUE TITLE
Duckduckgo before Wolfram Alpha?

### ISSUE THREAD

**Issue by valdr** [MycroftAI/fallback-duckduckgo#1]
I'm having trouble getting this to work...
Even uninstalling "fallback-wolfram-alpha" does not seem to remove the seemingly ever-present skill, and duckduckgo does not seem to get a chance.

**Comment by penrods** [comment]
I've noticed that there are instances when removing the skill via MSM/voice doesn't cause the skill to be unloaded from memory even if it is gone from the disk.  After a reboot does it work?

Also, the DuckDuckGo fallback uses their Instant Answer API (https://duckduckgo.com/api) which is not the necessarily the same as the answer card that appears on the https://www.duckduckgo.com website to the same query.  If you are unsure, you can try:
    What is bitcoin
Which should respond:
    "Bitcoin is a cryptocurrency and worldwide payment system."

The Wolfram Alpha fallback doesn't handle that query, so you know it is coming from DuckDuckGo if you get a response.

**Comment by valdr** [comment]
Updating to 18.08 has fixed this one...

Closing the issue.
